"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for LegalStatusValue' 
type: object
properties:
  legalstatus:
    type: string
    enum: ["agreed", "notAgreed"]
required:
  - legalstatus

