"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for AdministrativeBoundary' 
type: object
properties:
  nationallevel:
    description: 'Levels of administration in the national administrative hierarchy. This code list reflects the level in the hierarchical pyramid of the administrative structures, which is based on geometric aggregation of territories and does not necessarily describe the subordination between the related administrative authorities.'  
    type: string
    enum: ["1st order", "2nd order","3rd order","4th order","5th order","6th order"]
    description: >
            Sort order:
             * `1st order` - Highest level in the national administrative hierarchy
             * `2nd order` - 2nd level in the national administrative hierarchy
             * `3rd order` - 3nd level in the national administrative hierarchy
             * `4th order` - 4nd level in the national administrative hierarchy
             * `5th order` - 5nd level in the national administrative hierarchy
             * `6th order` - 6nd level in the national administrative hierarchy
required:   
  - nationallevel
