"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for AdministrativeBoundary' 
type: object
properties:
  localid:
    type: string
  country:
    type: string
  allOf:
    $ref: ../AdministrativeHierarchyLevel/schema.yaml   
  allOf:
    $ref: ../LegalStatusValue/schema.yaml    
  allOf: 
    $ref: ../TechnicalStatusValue/schema.yaml 
  administrativeunit1: 
    type: string 
  administrativeunit2: 
    type: string   
  beginlifespanversion:
    type: string
    format: date-time 
  namespace:
    type: string   
  versionid:
    type: string                
required:
  - localid
  - country
  - nationallevel
  - legalstatus
  - technicalstatus
  - administrativeunit1
  - administrativeunit2
  - beginlifespanversion
  - namespace 
  - versionid

 
